[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#[[plugins]]
#repo = 'Shougo/denite.nvim'
#hook_add = '''
#" Denite用プレフィックス
#nmap [denite] <Nop>
#nmap <C-j> [denite]
#
#nnoremap <silent> [denite]f :<C-u>DeniteBufferDir
#      \ -direction=topleft -cursor-wrap=true file file:new<CR>
#"バッファ一覧
#nnoremap <silent> [denite]b :<C-u>Denite -direction=topleft -cursor-wrap=true buffer<CR>
#"レジスタ一覧
#nnoremap <silent> [denite]r :<C-u>Denite -direction=topleft -cursor-wrap=true -buffer-name=register register<CR>
#"最近使用したファイル一覧
#nnoremap <silent> [denite]m :<C-u>Denite -direction=topleft -cursor-wrap=true file_mru<CR>
#
#" 上下移動を<C-N>, <C-P>
#call denite#custom#map('normal', '<C-j>', '<denite:move_to_next_line>')
#call denite#custom#map('normal', '<C-k>', '<denite:move_to_previous_line>')
#call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>')
#call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>')
#" 入力履歴移動を<C-J>, <C-K>
#call denite#custom#map('insert', '<C-n>', '<denite:assign_next_text>')
#call denite#custom#map('insert', '<C-p>', '<denite:assign_previous_text>')
#" 横割りオープンを`<C-S>`
#call denite#custom#map('insert', '<C-S>', '<denite:do_action:split>')
#" 縦割りオープンを`<C-I>`
#call denite#custom#map('insert', '<C-I>', '<denite:do_action:vsplit>')
#" タブオープンを`<C-O>`
#call denite#custom#map('insert', '<C-O>', '<denite:do_action:tabopen>')
#
#" file_rec検索時にfuzzymatchを有効にし、検索対象から指定のファイルを除外
#call denite#custom#source(
#    \ 'file_rec', 'matchers', ['matcher_fuzzy', 'matcher_project_files', 'matcher_ignore_globs'])
#
#" 検索対象外のファイル指定
#call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
#    \ [ '.git/', '.ropeproject/', '__pycache__/',
#    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])
#'''
